language: go

go:
  - 1.14.x

os: linux

dist: bionic

env:
  - GO111MODULE=on

before_install:

install:

before_script:

script:
  - go vet ./...
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
  - go build

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

after_success:
  - bash <(curl -s https://codecov.io/bash)
