name: TBD
on: [push]
jobs:
  doit:
    name: tbd
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.18
      - name: cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: |
            ${{ runner.os }}-build-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/go.mod') }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: vet
        run: |
          go vet ./...
      - name: test
        run: |
          go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: build
        env:
          CGO_ENABLED: 0
        run: |
          go build -buildmode=pie -trimpath -ldflags "-s -w -buildid="
      - name: artifact
        uses: actions/upload-artifact@v3
        with:
          name: indieweb-glue
          path: indieweb-glue
          retention-days: 1
      - name: trigger deploy
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}